[build]
  publish = "dist"
  command = "npx expo export --platform web"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/kruoka-lookup"
  to = "/.netlify/functions/kruoka-lookup"
  status = 200

[[redirects]]
  from = "/api/vision"
  to = "/.netlify/functions/vision"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
